# Generated by Django 4.2.1 on 2023-08-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
