# Generated by Django 4.2.1 on 2023-08-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_hobby_title_alter_hobby_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.ManyToManyField(to='users.hobby'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby_en',
            field=models.ManyToManyField(null=True, to='users.hobby'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby_ru',
            field=models.ManyToManyField(null=True, to='users.hobby'),
        ),
    ]
