# Generated by Django 4.2.1 on 2023-08-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_hobby_alter_user_hobby_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
