# Generated by Django 4.2.1 on 2023-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='residence_city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='residence_city'),
        ),
    ]
